# Generated by Django 4.2.3 on 2023-07-13 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
