# Generated by Django 4.2.3 on 2023-07-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_content_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='created_date',
            new_name='createdDate',
        ),
    ]
